# Generated by Django 6.0.5 on 2026-05-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('title', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darsliklar', to='fanlar.fanlar')),
            ],
            options={
                'db_table': 'darslik',
            },
        ),
    ]
