# Generated by Django 6.0.5 on 2026-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True)),
                ('photo', models.ImageField(upload_to='image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('title', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'darslik',
            },
        ),
    ]
