# Generated by Django 6.0.5 on 2026-06-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo')),
                ('Video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('Pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('describe', models.TextField(verbose_name='Describe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fan_nomi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='darsliklar', to='fanlar.fanlar', verbose_name='Fan_nomi')),
            ],
            options={
                'db_table': 'darslik',
            },
        ),
    ]
