# Generated by Django 6.0.5 on 2026-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darslik',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
