# Generated by Django 6.0.5 on 2026-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darslik',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
