# Generated by Django 6.0.5 on 2026-05-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0001_initial'),
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darslik',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='darsliklar', to='fanlar.fanlar'),
        ),
    ]
