# Generated by Django 6.0.5 on 2026-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0002_alter_darslik_fan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darslik',
            old_name='fan',
            new_name='fan_nomi',
        ),
    ]
