# Generated by Django 6.0.5 on 2026-06-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0002_alter_darslik_update_at'),
        ('fanlar', '0003_alter_fanlar_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darslik',
            old_name='pdf',
            new_name='Pdf',
        ),
        migrations.RenameField(
            model_name='darslik',
            old_name='video',
            new_name='Video',
        ),
        migrations.AlterField(
            model_name='darslik',
            name='describe',
            field=models.TextField(verbose_name='Describe'),
        ),
        migrations.AlterField(
            model_name='darslik',
            name='fan_nomi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='darsliklar', to='fanlar.fanlar', verbose_name='Fan_nomi'),
        ),
        migrations.AlterField(
            model_name='darslik',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='darslik',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
