# Generated by Django 6.0.5 on 2026-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0002_alter_darslik_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darslik',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
