# Generated by Django 6.0.5 on 2026-06-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanlar',
            name='image',
        ),
    ]
