# Generated by Django 6.0.5 on 2026-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0002_remove_fanlar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
